### ISSUE TITLE
feat: multisignature support based on AIP18

### ISSUE THREAD

**Issue by kristjank** [ArkEcosystem/core#2090] opened 2019-02-12 10:59 UTC
Implement support for multi signature transactions, based on AIP18 proposal - https://github.com/ArkEcosystem/AIPs/blob/master/AIPS/aip-18.md

**Comment by faustbrian** [comment] 2019-02-12 11:15
Duplicate of https://github.com/ArkEcosystem/core/issues/1590

**Closed by faustbrian** 2019-02-12 11:15 UTC
Labels: Type: Feature
