### ISSUE TITLE
Devnet Sync Error.  The node version is 2.0.12.

### ISSUE THREAD

**Issue by leeheejoo** [ArkEcosystem/core#1672] opened 2018-12-07 04:19 UTC
**On a devnet, a certain block fails to synchronize after an error occurs.**

**This occurs after updating from 2.0.1 to 2.0.12.**

[2018-12-07 12:18:22][DEBUG]   : Delegate stevenhop (0304d0c477d634cc85d89c1a4afee8f51168d1747fe8fd79cabc26565e49eb8a7a) allowed to forge block 935,935 👍
[2018-12-07 12:18:22][ERROR]   : Can't apply transaction id:0271dfb4623b9f0d8cdcad732025da454454f88d9fdb85189a7cb6b2fa8ee05d from sender:D6Z26L69gdk9qYmTv5uzk3uGepigtHY4ax due to ["Invalid second-signature field"]
[2018-12-07 12:18:22][DEBUG]   : Audit: [
  {
    "Remaining amount": 12393903988487604
  },
  {
    "Signature validation": true
  },
  {
    "Transfer": true
  }
]
[2018-12-07 12:18:22][ERROR]   : Failed to apply all transactions in block - reverting previous transactions
[2018-12-07 12:18:22][ERROR]   : Refused new block {"version":0,"timestamp":53985522,"height":935935,"previousBlockHex":"47d4abdc15194fc0","previousBlock":"5175950833490677696","numberOfTransactions":100,"totalAmount":"1000000000000","totalFee":"1000000000","reward":"200000000","payloadLength":3200,"payloadHash":"00ac478792f9766697698ece152bbbf5c617e9b7120c4080f8c4251facd43aec","generatorPublicKey":"0304d0c477d634cc85d89c1a4afee8f51168d1747fe8fd79cabc26565e49eb8a7a","blockSignature":"3045022100d87fbebfc87e7971580ffa85adca3792c5a1bdf4dd4526d8063a0f5ef777982802203039c7da3876ec99ca957d7398cea56f9ccd4440ef455e17480bb9517b4693cd","id":"12088909655096415741","idHex":"a7c46f4811cfd5fd"}
[2018-12-07 12:18:22][DEBUG]   : Error: Can't apply transaction 0271dfb4623b9f0d8cdcad732025da454454f88d9fdb85189a7cb6b2fa8ee05d
    at WalletManager.applyTransaction (/home/testuser/core/packages/core-database/lib/wallet-manager.js:469:13)
    at block.transactions.forEach.transaction (/home/testuser/core/packages/core-database/lib/wallet-manager.js:330:14)
    at Array.forEach (<anonymous>)
    at WalletManager.applyBlock (/home/testuser/core/packages/core-database/lib/wallet-manager.js:329:26)
    at PostgresConnection.applyBlock (/home/testuser/core/packages/core-database/lib/interface.js:446:24)
[2018-12-07 12:18:22][DEBUG]   : event 'FORK': {"syncWithNetwork":"downloadBlocks"} -> {"fork":"analysing"} -> actions: [startForkRecovery, analyseFork]
[2018-12-07 12:18:22][DEBUG]   : Blockchain not ready to accept new block at height 935,936. Last block: 935,934 ⚠️

**I deleted the db on the Devnet and created it again. And I started syncing from the beginning.
Synchronization errors still occur.**

[2018-12-07 13:09:46][DEBUG]   : Delegate darkgalp (037997a6553ea8073eb199e9f5ff23b8f0892e79433ef35e13966e0a12849d02e3) allowed to forge block 8,695 👍
[2018-12-07 13:09:46][ERROR]   : Can't apply transaction id:5f8adc34a55ca86b512cec4abfd3e1d909d42500ca6971b6c45f07ffc2a14d0e from sender:DNjuJEDQkhrJ7cA9FZ2iVXt5anYiM8Jtc9 due to ["Invalid second-signature field"]
[2018-12-07 13:09:46][DEBUG]   : Audit: [
  {
    "Remaining amount": 49997498000000
  },
  {
    "Signature validation": true
  },
  {
    "Transfer": true
  }
]
[2018-12-07 13:09:46][ERROR]   : Failed to apply all transactions in block - reverting previous transactions
[2018-12-07 13:09:46][ERROR]   : Refused new block {"version":0,"timestamp":45091634,"height":8695,"previousBlockHex":"17cb9a8263f83407","previousBlock":"1714633967958242311","numberOfTransactions":1,"totalAmount":"12000000","totalFee":"10000000","reward":"0","payloadLength":32,"payloadHash":"c55b71d45d84bbd173757c291291b34c8813d510b6353650ccb5da419a9ad8fe","generatorPublicKey":"037997a6553ea8073eb199e9f5ff23b8f0892e79433ef35e13966e0a12849d02e3","blockSignature":"3044022005cc216412616c8f885ee7dbf47306146dd7a1f9299d91432acfc173d7ab6caf02207b5d386a598d840a44931ac1eafe2d1e61a14fd68fcb1fc6b7d983abc4682c48","id":"12825231977760889526","idHex":"b1fc6088646b1ab6"}
[2018-12-07 13:09:46][DEBUG]   : Error: Can't apply transaction 5f8adc34a55ca86b512cec4abfd3e1d909d42500ca6971b6c45f07ffc2a14d0e
    at WalletManager.applyTransaction (/home/coin/core/packages/core-database/lib/wallet-manager.js:469:13)
    at block.transactions.forEach.transaction (/home/coin/core/packages/core-database/lib/wallet-manager.js:330:14)
    at Array.forEach (<anonymous>)
    at WalletManager.applyBlock (/home/coin/core/packages/core-database/lib/wallet-manager.js:329:26)
    at PostgresConnection.applyBlock (/home/coin/core/packages/core-database/lib/interface.js:446:24)
    at process._tickCallback (internal/process/next_tick.js:68:7)
[2018-12-07 13:09:46][DEBUG]   : Blockchain not ready to accept new block at height 8,696. Last block: 8,694 ⚠️

**Comment by JeremiGendron** [comment] 2018-12-07 20:59
I had a similar error and the answer was to remove ~/.npm ~/.yarn as well as node_modules and node_gyp wherever they occur. This was on a clean machine, I think the issue was with a compiled sql driver in node_gyp.

**Comment by zillionn** [comment] 2018-12-08 09:12
The problem is not with you, there wasn't a check for the second signature and some txs were send with second signature, but the sender doesn't have a second public key. After the patch #1658 these txs fail validation. Maybe they should be added to the exceptions.

**Comment by roks0n** [comment] 2018-12-08 09:44
Ah perfect, I already started adding them there and can open a PR once everything passes. This discussion lead me to think there's a different elsewhere.

**Comment by roks0n** [comment] 2018-12-08 10:01
Omg, there's so many of these txs 😩

**Comment by zillionn** [comment] 2018-12-08 10:17
Yes, they're too many, maybe the better solution is to skip that check on `devnet`... @supaiku0

**Comment by zillionn** [comment] 2018-12-08 10:47
Hm, maybe my list is off. Can you send yours so we can test?

**Comment by roks0n** [comment] 2018-12-08 10:49
@zillionn I've just open a PR: https://github.com/ArkEcosystem/core/pull/1675

**Comment by faustbrian** [comment] 2018-12-21 06:39
Resolved by https://github.com/ArkEcosystem/core/commit/30ab06d11cc62f2ee3d6350a048b63d1e8db752b

**Closed by faustbrian** 2018-12-21 06:39 UTC
Labels: :skull_and_crossbones: bug
