### ISSUE TITLE
Transactions endpoint is slow before being cached

### ISSUE THREAD

**Issue by alexbarnsley** [ArkEcosystem/core#3200] opened 2019-11-04 09:59 UTC
While using the desktop wallet, it seems the transactions endpoint has slowed down. The timeout hasn't been changed on the wallet (5 seconds). This only happens on the first request, subsequent requests (where the data has not changed) works fine. I can provide a video example if needed. Tested on a few different peers.

**Expected Behavior**
Shouldn't be slower than 2.5

**Current Behavior**
Slower than 2.5

**Possible Solution**
Speed it up

**Steps to Reproduce (for bugs)**
When viewing wallets in the desktop wallet, the transaction list may appear empty or take a while to load. Pressing the "refresh" icon then loads the data.

**Comment by supaiku0** [comment] 2019-11-08 00:03
@alexbarnsley This turned out to be a non-Core issue?

**Comment by faustbrian** [comment] 2019-11-08 05:06
It seems to be a disk issue on certain machines, on servers with nvme disks there are no issues at all or at least it is difficult to reproduce it consistently.

**Comment by vasild** [comment] 2019-12-06 13:10
Closing as non-core issue. Please reopen if more information is available that shows this might be a core issue.

**Closed by vasild** 2019-12-06 13:10 UTC
